language: golang

go:
  - tip

env:
  global:
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"

install:
  - go get github.com/gin-gonic/gin
  - go get github.com/go-redis/redis
  - go get github.com/stretchr/testify/assert

services:
  - redis-server

script:
  - go test -v -cover
