language: golang

go:
  - tip

env:
  global:
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"

install:
  - GO111MODULE=on go mod tidy

services:
  - redis-server

script:
  - go test -v
